appName: webapp-using-helm

namespace: default

replicaCount: 1

image:
  repository: savolylali/web-app
  pullPolicy: IfNotPresent
  tag: "latest"


service:
  type: ClusterIP
  port: 80


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 16Mi