# Default values for webapp-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: savolylali/web-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 8080

ingress:
  enabled: false
  annotations: { }
  hosts:
    - host: lali.local
      paths: [ ]
  tls: [ ]
