name: Terraform CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: cd webapp/terraform && terraform init

      - name: Terraform Plan
        run: cd webapp/terraform && terraform plan

      - name: Terraform Apply
        run: cd webapp/terraform && terraform apply -auto-approve