name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: cd webapp && docker build -t web-app .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: web-app
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os, library'
          severity: 'CRITICAL, HIGH'

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag web-app ${{ secrets.DOCKERHUB_USERNAME }}/web-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-app:${{ github.sha }}