name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: cd webapp && docker build -t web-app:${GITHUB_SHA} .

      - name: Container Security Check
        run: |
          docker run --rm -v $(pwd)/webapp:/workdir aquasec/trivy:latest web-app:${GITHUB_SHA}

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag web-app:${GITHUB_SHA} ${{ secrets.DOCKERHUB_USERNAME }}/web-app:${GITHUB_SHA}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-app:${GITHUB_SHA}